copy ..\gs\equip_config.h .\
copy ..\gs\equip_config.cpp .\
copy ..\gs\equip_operation.h .\
copy ..\gs\equip_operation.cpp .\
copy ..\gs\guild_config.h .\
copy ..\gs\guild_config.cpp .\
copy ..\gs\item_config.h .\
copy ..\gs\item_config.cpp .\
copy ..\gs\item_def.h .\
copy ..\gs\item_operation.h .\
copy ..\gs\item_operation.cpp .\
copy ..\gs\mission_config.h .\
copy ..\gs\mission_config.cpp .\
copy ..\gs\mission_fight.h .\
copy ..\gs\mission_fight.cpp .\
copy ..\gs\mission_operation.h .\
copy ..\gs\mission_operation.cpp .\
copy ..\gs\player_config.h .\
copy ..\gs\player_config.cpp .\
copy ..\gs\role_config.h .\
copy ..\gs\role_config.cpp .\
copy ..\gs\role_operation.h .\
copy ..\gs\role_operation.cpp .\
copy ..\gs\treasure_config.h .\
copy ..\gs\treasure_config.cpp .\
copy ..\gs\treasure_list.h .\
copy ..\gs\treasure_list.cpp .\
copy ..\gs\sport_config.h .\
copy ..\gs\sport_config.cpp .\
copy ..\gs\pvp_config.h .\
copy ..\gs\pvp_config.cpp .\

pause