//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guild_member.eproto
namespace dhc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"guild_member_t")]
  public partial class guild_member_t : global::ProtoBuf.IExtensible
  {
    public guild_member_t() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private ulong _guild_guid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guild_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guild_guid
    {
      get { return _guild_guid; }
      set { _guild_guid = value; }
    }
    private ulong _player_guid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_guid
    {
      get { return _player_guid; }
      set { _player_guid = value; }
    }
    private int _player_iocn_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"player_iocn_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_iocn_id
    {
      get { return _player_iocn_id; }
      set { _player_iocn_id = value; }
    }
    private string _player_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private int _player_level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"player_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_level
    {
      get { return _player_level; }
      set { _player_level = value; }
    }
    private int _bf = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bf
    {
      get { return _bf; }
      set { _bf = value; }
    }
    private int _zhiwu = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"zhiwu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zhiwu
    {
      get { return _zhiwu; }
      set { _zhiwu = value; }
    }
    private int _sign_flag = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sign_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sign_flag
    {
      get { return _sign_flag; }
      set { _sign_flag = value; }
    }
    private ulong _last_sign_time = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"last_sign_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_sign_time
    {
      get { return _last_sign_time; }
      set { _last_sign_time = value; }
    }
    private ulong _join_time = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"join_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong join_time
    {
      get { return _join_time; }
      set { _join_time = value; }
    }
    private int _contribution = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"contribution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contribution
    {
      get { return _contribution; }
      set { _contribution = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _honors = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"honors", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> honors
    {
      get { return _honors; }
    }
  
    private int _mnum = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"mnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mnum
    {
      get { return _mnum; }
      set { _mnum = value; }
    }
    private int _mbnum = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"mbnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mbnum
    {
      get { return _mbnum; }
      set { _mbnum = value; }
    }
    private ulong _last_mbtime = default(ulong);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"last_mbtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_mbtime
    {
      get { return _last_mbtime; }
      set { _last_mbtime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _mission_rewards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"mission_rewards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mission_rewards
    {
      get { return _mission_rewards; }
    }
  
    private int _msg_count = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"msg_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int msg_count
    {
      get { return _msg_count; }
      set { _msg_count = value; }
    }
    private int _player_vip = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"player_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_vip
    {
      get { return _player_vip; }
      set { _player_vip = value; }
    }
    private int _player_achieve = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"player_achieve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_achieve
    {
      get { return _player_achieve; }
      set { _player_achieve = value; }
    }
    private ulong _offline_time = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"offline_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong offline_time
    {
      get { return _offline_time; }
      set { _offline_time = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _gongpo_rewards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"gongpo_rewards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> gongpo_rewards
    {
      get { return _gongpo_rewards; }
    }
  
    private int _map_star = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"map_star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_star
    {
      get { return _map_star; }
      set { _map_star = value; }
    }
    private int _nalflag = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"nalflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nalflag
    {
      get { return _nalflag; }
      set { _nalflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}