//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guild.eproto
namespace dhc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"guild_t")]
  public partial class guild_t : global::ProtoBuf.IExtensible
  {
    public guild_t() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _icon = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _gonggao = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gonggao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gonggao
    {
      get { return _gonggao; }
      set { _gonggao = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _bftj = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bftj", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bftj
    {
      get { return _bftj; }
      set { _bftj = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _member_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(8, Name=@"member_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> member_guids
    {
      get { return _member_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _event_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(9, Name=@"event_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> event_guids
    {
      get { return _event_guids; }
    }
  
    private ulong _last_boss_time = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"last_boss_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_boss_time
    {
      get { return _last_boss_time; }
      set { _last_boss_time = value; }
    }
    private ulong _last_daily_time = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"last_daily_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_daily_time
    {
      get { return _last_daily_time; }
      set { _last_daily_time = value; }
    }
    private ulong _last_week_time = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"last_week_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_week_time
    {
      get { return _last_week_time; }
      set { _last_week_time = value; }
    }
    private string _leader_name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private int _honor = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int honor
    {
      get { return _honor; }
      set { _honor = value; }
    }
    private ulong _mission = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"mission", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mission
    {
      get { return _mission; }
      set { _mission = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _message_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(20, Name=@"message_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> message_guids
    {
      get { return _message_guids; }
    }
  
    private int _mobai_num = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"mobai_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mobai_num
    {
      get { return _mobai_num; }
      set { _mobai_num = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skill_ids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"skill_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill_ids
    {
      get { return _skill_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _skill_levels = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"skill_levels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill_levels
    {
      get { return _skill_levels; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _apply_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(24, Name=@"apply_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> apply_guids
    {
      get { return _apply_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _apply_names = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(25, Name=@"apply_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> apply_names
    {
      get { return _apply_names; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _apply_template = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(26, Name=@"apply_template", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_template
    {
      get { return _apply_template; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _apply_level = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(27, Name=@"apply_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_level
    {
      get { return _apply_level; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _apply_bf = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(28, Name=@"apply_bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_bf
    {
      get { return _apply_bf; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _apply_vip = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(29, Name=@"apply_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_vip
    {
      get { return _apply_vip; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _apply_achieve = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(30, Name=@"apply_achieve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_achieve
    {
      get { return _apply_achieve; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _shop_ids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(31, Name=@"shop_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> shop_ids
    {
      get { return _shop_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _shop_nums = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(32, Name=@"shop_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> shop_nums
    {
      get { return _shop_nums; }
    }
  
    private int _last_level = default(int);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"last_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int last_level
    {
      get { return _last_level; }
      set { _last_level = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _red_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(34, Name=@"red_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> red_guids
    {
      get { return _red_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _box_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(35, Name=@"box_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> box_guids
    {
      get { return _box_guids; }
    }
  
    private int _change_name = default(int);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"change_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int change_name
    {
      get { return _change_name; }
      set { _change_name = value; }
    }
    private int _juntuan_apply = default(int);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"juntuan_apply", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int juntuan_apply
    {
      get { return _juntuan_apply; }
      set { _juntuan_apply = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _pvp_guilds = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(38, Name=@"pvp_guilds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> pvp_guilds
    {
      get { return _pvp_guilds; }
    }
  
    private ulong _pvp_guild = default(ulong);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"pvp_guild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pvp_guild
    {
      get { return _pvp_guild; }
      set { _pvp_guild = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _apply_nalfags = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(40, Name=@"apply_nalfags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> apply_nalfags
    {
      get { return _apply_nalfags; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}