//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg_team.proto
// Note: requires additional types generated from: role.eproto
// Note: requires additional types generated from: equip.eproto
// Note: requires additional types generated from: treasure.eproto
namespace protocol.team
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"team_player")]
  public partial class team_player : global::ProtoBuf.IExtensible
  {
    public team_player() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _bf = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bf
    {
      get { return _bf; }
      set { _bf = value; }
    }
    private int _chenhao = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chenhao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chenhao
    {
      get { return _chenhao; }
      set { _chenhao = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private bool _leader = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool leader
    {
      get { return _leader; }
      set { _leader = value; }
    }
    private bool _prepare = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"prepare", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool prepare
    {
      get { return _prepare; }
      set { _prepare = value; }
    }
    private int _reward_num = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reward_num
    {
      get { return _reward_num; }
      set { _reward_num = value; }
    }
    private bool _is_npc = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"is_npc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_npc
    {
      get { return _is_npc; }
      set { _is_npc = value; }
    }
    private int _serverid = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }
    private int _kill = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"kill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int kill
    {
      get { return _kill; }
      set { _kill = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _achieve = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"achieve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieve
    {
      get { return _achieve; }
      set { _achieve = value; }
    }
    private int _guanghuan = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"guanghuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guanghuan
    {
      get { return _guanghuan; }
      set { _guanghuan = value; }
    }
    private int _dress = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _invites = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(17, Name=@"invites", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> invites
    {
      get { return _invites; }
    }
  
    private ulong _bind_guid = default(ulong);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"bind_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bind_guid
    {
      get { return _bind_guid; }
      set { _bind_guid = value; }
    }
    private int _nalflag = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"nalflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nalflag
    {
      get { return _nalflag; }
      set { _nalflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"team")]
  public partial class team : global::ProtoBuf.IExtensible
  {
    public team() {}
    
    private ulong _team_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.team.team_player> _players = new global::System.Collections.Generic.List<protocol.team.team_player>();
    [global::ProtoBuf.ProtoMember(2, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.team.team_player> players
    {
      get { return _players; }
    }
  
    private bool _open = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool open
    {
      get { return _open; }
      set { _open = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _jiacheng = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jiacheng", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jiacheng
    {
      get { return _jiacheng; }
      set { _jiacheng = value; }
    }
    private bool _result = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _stat = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private bool _fight = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"team_invite")]
  public partial class team_invite : global::ProtoBuf.IExtensible
  {
    public team_invite() {}
    
    private ulong _invite_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"invite_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong invite_id
    {
      get { return _invite_id; }
      set { _invite_id = value; }
    }
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _chenghao = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chenghao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chenghao
    {
      get { return _chenghao; }
      set { _chenghao = value; }
    }
    private int _bf = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bf
    {
      get { return _bf; }
      set { _bf = value; }
    }
    private string _guild = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"guild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild
    {
      get { return _guild; }
      set { _guild = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _achieve = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"achieve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieve
    {
      get { return _achieve; }
      set { _achieve = value; }
    }
    private ulong _team_id = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _nalflag = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"nalflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nalflag
    {
      get { return _nalflag; }
      set { _nalflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bingyuan_huihe")]
  public partial class bingyuan_huihe : global::ProtoBuf.IExtensible
  {
    public bingyuan_huihe() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _team_ids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"team_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> team_ids
    {
      get { return _team_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _team_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"team_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> team_guids
    {
      get { return _team_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _max_hps = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(3, Name=@"max_hps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> max_hps
    {
      get { return _max_hps; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _hps = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(4, Name=@"hps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> hps
    {
      get { return _hps; }
    }
  
    private ulong _win = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong win
    {
      get { return _win; }
      set { _win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bingyuan_fight_text")]
  public partial class bingyuan_fight_text : global::ProtoBuf.IExtensible
  {
    public bingyuan_fight_text() {}
    
    private readonly global::System.Collections.Generic.List<protocol.team.bingyuan_huihe> _huihes = new global::System.Collections.Generic.List<protocol.team.bingyuan_huihe>();
    [global::ProtoBuf.ProtoMember(1, Name=@"huihes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.team.bingyuan_huihe> huihes
    {
      get { return _huihes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_enter_world")]
  public partial class cmsg_enter_world : global::ProtoBuf.IExtensible
  {
    public cmsg_enter_world() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _sig = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sig
    {
      get { return _sig; }
      set { _sig = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_enter_world")]
  public partial class smsg_enter_world : global::ProtoBuf.IExtensible
  {
    public smsg_enter_world() {}
    
    private int _chenghao = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chenghao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chenghao
    {
      get { return _chenghao; }
      set { _chenghao = value; }
    }
    private int _point = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private ulong _next_invite_time = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"next_invite_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong next_invite_time
    {
      get { return _next_invite_time; }
      set { _next_invite_time = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.team.team_invite> _invites = new global::System.Collections.Generic.List<protocol.team.team_invite>();
    [global::ProtoBuf.ProtoMember(5, Name=@"invites", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.team.team_invite> invites
    {
      get { return _invites; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _talks = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"talks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> talks
    {
      get { return _talks; }
    }
  
    private int _srank = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"srank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int srank
    {
      get { return _srank; }
      set { _srank = value; }
    }
    private int _sgrank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sgrank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sgrank
    {
      get { return _sgrank; }
      set { _sgrank = value; }
    }
    private int _spoint = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"spoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spoint
    {
      get { return _spoint; }
      set { _spoint = value; }
    }
    private int _sduanwei = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sduanwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sduanwei
    {
      get { return _sduanwei; }
      set { _sduanwei = value; }
    }
    private bool _sreset = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sreset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool sreset
    {
      get { return _sreset; }
      set { _sreset = value; }
    }
    private int _soduanwei = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"soduanwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soduanwei
    {
      get { return _soduanwei; }
      set { _soduanwei = value; }
    }
    private ulong _ds_cdtime = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ds_cdtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ds_cdtime
    {
      get { return _ds_cdtime; }
      set { _ds_cdtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_create")]
  public partial class smsg_team_create : global::ProtoBuf.IExtensible
  {
    public smsg_team_create() {}
    
    private protocol.team.team _team_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"team_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.team.team team_info
    {
      get { return _team_info; }
      set { _team_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_team_enter")]
  public partial class cmsg_team_enter : global::ProtoBuf.IExtensible
  {
    public cmsg_team_enter() {}
    
    private ulong _team_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_enter")]
  public partial class smsg_team_enter : global::ProtoBuf.IExtensible
  {
    public smsg_team_enter() {}
    
    private protocol.team.team_player _member = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.team.team_player member
    {
      get { return _member; }
      set { _member = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _jiacheng = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jiacheng", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jiacheng
    {
      get { return _jiacheng; }
      set { _jiacheng = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_leave")]
  public partial class smsg_team_leave : global::ProtoBuf.IExtensible
  {
    public smsg_team_leave() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private ulong _leader = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong leader
    {
      get { return _leader; }
      set { _leader = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _jiacheng = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jiacheng", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jiacheng
    {
      get { return _jiacheng; }
      set { _jiacheng = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_team_kick")]
  public partial class cmsg_team_kick : global::ProtoBuf.IExtensible
  {
    public cmsg_team_kick() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_prepare")]
  public partial class smsg_team_prepare : global::ProtoBuf.IExtensible
  {
    public smsg_team_prepare() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private bool _prepare = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prepare", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool prepare
    {
      get { return _prepare; }
      set { _prepare = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_team_move")]
  public partial class cmsg_team_move : global::ProtoBuf.IExtensible
  {
    public cmsg_team_move() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_move")]
  public partial class smsg_team_move : global::ProtoBuf.IExtensible
  {
    public smsg_team_move() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_fight_team")]
  public partial class smsg_fight_team : global::ProtoBuf.IExtensible
  {
    public smsg_fight_team() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _win = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong win
    {
      get { return _win; }
      set { _win = value; }
    }
    private protocol.team.bingyuan_fight_text _text = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.team.bingyuan_fight_text text
    {
      get { return _text; }
      set { _text = value; }
    }
    private protocol.team.team _oteam = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oteam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.team.team oteam
    {
      get { return _oteam; }
      set { _oteam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_chat_team")]
  public partial class cmsg_chat_team : global::ProtoBuf.IExtensible
  {
    public cmsg_chat_team() {}
    
    private string _text = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private string _color = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string color
    {
      get { return _color; }
      set { _color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_chat_team")]
  public partial class smsg_chat_team : global::ProtoBuf.IExtensible
  {
    public smsg_chat_team() {}
    
    private ulong _player_guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_guid
    {
      get { return _player_guid; }
      set { _player_guid = value; }
    }
    private string _player_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private uint _player_template = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_template", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_template
    {
      get { return _player_template; }
      set { _player_template = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _text = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private string _color = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _player_nalflag = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"player_nalflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_nalflag
    {
      get { return _player_nalflag; }
      set { _player_nalflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_player_look")]
  public partial class cmsg_player_look : global::ProtoBuf.IExtensible
  {
    public cmsg_player_look() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_player_look")]
  public partial class smsg_player_look : global::ProtoBuf.IExtensible
  {
    public smsg_player_look() {}
    
    private uint _template_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint template_id
    {
      get { return _template_id; }
      set { _template_id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _bf = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bf
    {
      get { return _bf; }
      set { _bf = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private readonly global::System.Collections.Generic.List<dhc.role_t> _roles = new global::System.Collections.Generic.List<dhc.role_t>();
    [global::ProtoBuf.ProtoMember(6, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dhc.role_t> roles
    {
      get { return _roles; }
    }
  
    private readonly global::System.Collections.Generic.List<dhc.equip_t> _equips = new global::System.Collections.Generic.List<dhc.equip_t>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dhc.equip_t> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<dhc.treasure_t> _treasures = new global::System.Collections.Generic.List<dhc.treasure_t>();
    [global::ProtoBuf.ProtoMember(8, Name=@"treasures", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dhc.treasure_t> treasures
    {
      get { return _treasures; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _duixings = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"duixings", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> duixings
    {
      get { return _duixings; }
    }
  
    private string _guild = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"guild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild
    {
      get { return _guild; }
      set { _guild = value; }
    }
    private int _achieves = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"achieves", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieves
    {
      get { return _achieves; }
      set { _achieves = value; }
    }
    private int _nalflag = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"nalflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nalflag
    {
      get { return _nalflag; }
      set { _nalflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_invite_add")]
  public partial class smsg_invite_add : global::ProtoBuf.IExtensible
  {
    public smsg_invite_add() {}
    
    private protocol.team.team_invite _invite = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"invite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.team.team_invite invite
    {
      get { return _invite; }
      set { _invite = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_invite_agree")]
  public partial class cmsg_invite_agree : global::ProtoBuf.IExtensible
  {
    public cmsg_invite_agree() {}
    
    private bool _agree = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private ulong _invite_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"invite_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong invite_id
    {
      get { return _invite_id; }
      set { _invite_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_invite_remove")]
  public partial class smsg_invite_remove : global::ProtoBuf.IExtensible
  {
    public smsg_invite_remove() {}
    
    private ulong _invite_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"invite_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong invite_id
    {
      get { return _invite_id; }
      set { _invite_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_invite_remove_social")]
  public partial class smsg_invite_remove_social : global::ProtoBuf.IExtensible
  {
    public smsg_invite_remove_social() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_invite_all")]
  public partial class smsg_invite_all : global::ProtoBuf.IExtensible
  {
    public smsg_invite_all() {}
    
    private ulong _next_time = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"next_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong next_time
    {
      get { return _next_time; }
      set { _next_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_team_player_reward_change")]
  public partial class smsg_team_player_reward_change : global::ProtoBuf.IExtensible
  {
    public smsg_team_player_reward_change() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _point = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _chenghao = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chenghao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chenghao
    {
      get { return _chenghao; }
      set { _chenghao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_change_team_stat")]
  public partial class smsg_change_team_stat : global::ProtoBuf.IExtensible
  {
    public smsg_change_team_stat() {}
    
    private int _stat = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_hanhua")]
  public partial class cmsg_hanhua : global::ProtoBuf.IExtensible
  {
    public cmsg_hanhua() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_hanhua")]
  public partial class smsg_hanhua : global::ProtoBuf.IExtensible
  {
    public smsg_hanhua() {}
    
    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cmsg_change_hanhua")]
  public partial class cmsg_change_hanhua : global::ProtoBuf.IExtensible
  {
    public cmsg_change_hanhua() {}
    
    private readonly global::System.Collections.Generic.List<int> _index = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> index
    {
      get { return _index; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _content = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> content
    {
      get { return _content; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_fight_ds")]
  public partial class smsg_fight_ds : global::ProtoBuf.IExtensible
  {
    public smsg_fight_ds() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _text = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _duanwei = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"duanwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int duanwei
    {
      get { return _duanwei; }
      set { _duanwei = value; }
    }
    private int _bf = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bf
    {
      get { return _bf; }
      set { _bf = value; }
    }
    private int _template_id = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int template_id
    {
      get { return _template_id; }
      set { _template_id = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _achieve = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"achieve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieve
    {
      get { return _achieve; }
      set { _achieve = value; }
    }
    private int _guanghuan = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"guanghuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guanghuan
    {
      get { return _guanghuan; }
      set { _guanghuan = value; }
    }
    private int _dress = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dress
    {
      get { return _dress; }
      set { _dress = value; }
    }
    private ulong _cd_time = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cd_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong cd_time
    {
      get { return _cd_time; }
      set { _cd_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"smsg_reset_ds")]
  public partial class smsg_reset_ds : global::ProtoBuf.IExtensible
  {
    public smsg_reset_ds() {}
    
    private int _oldduanwei = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oldduanwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int oldduanwei
    {
      get { return _oldduanwei; }
      set { _oldduanwei = value; }
    }
    private int _newduanwei = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newduanwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newduanwei
    {
      get { return _newduanwei; }
      set { _newduanwei = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}