// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtool.eproto

#ifndef PROTOBUF_INCLUDED_gtool_2eeproto
#define PROTOBUF_INCLUDED_gtool_2eeproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gtool_2eeproto 

namespace protobuf_gtool_2eeproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_gtool_2eeproto
namespace dhc {
class gtool_t;
class gtool_tDefaultTypeInternal;
extern gtool_tDefaultTypeInternal _gtool_t_default_instance_;
}  // namespace dhc
namespace google {
namespace protobuf {
template<> ::dhc::gtool_t* Arena::CreateMaybeMessage<::dhc::gtool_t>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dhc {

// ===================================================================

class gtool_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dhc.gtool_t) */ {
 public:
  gtool_t();
  virtual ~gtool_t();

  gtool_t(const gtool_t& from);

  inline gtool_t& operator=(const gtool_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  gtool_t(gtool_t&& from) noexcept
    : gtool_t() {
    *this = ::std::move(from);
  }

  inline gtool_t& operator=(gtool_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const gtool_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const gtool_t* internal_default_instance() {
    return reinterpret_cast<const gtool_t*>(
               &_gtool_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(gtool_t* other);
  friend void swap(gtool_t& a, gtool_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline gtool_t* New() const final {
    return CreateMaybeMessage<gtool_t>(NULL);
  }

  gtool_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<gtool_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const gtool_t& from);
  void MergeFrom(const gtool_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(gtool_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::uint64 guid() const;
  void set_guid(::google::protobuf::uint64 value);

  // uint64 num = 2;
  void clear_num();
  static const int kNumFieldNumber = 2;
  ::google::protobuf::uint64 num() const;
  void set_num(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:dhc.gtool_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 guid_;
  ::google::protobuf::uint64 num_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gtool_2eeproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// gtool_t

// uint64 guid = 1;
inline void gtool_t::clear_guid() {
  set_changed();
  guid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 gtool_t::guid() const {
  // @@protoc_insertion_point(field_get:dhc.gtool_t.guid)
  return guid_;
}
inline void gtool_t::set_guid(::google::protobuf::uint64 value) {
  set_changed();
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:dhc.gtool_t.guid)
}

// uint64 num = 2;
inline void gtool_t::clear_num() {
  set_changed();
  num_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 gtool_t::num() const {
  // @@protoc_insertion_point(field_get:dhc.gtool_t.num)
  return num_;
}
inline void gtool_t::set_num(::google::protobuf::uint64 value) {
  set_changed();
  
  num_ = value;
  // @@protoc_insertion_point(field_set:dhc.gtool_t.num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dhc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gtool_2eeproto
