// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: other.proto

#ifndef PROTOBUF_INCLUDED_other_2eproto
#define PROTOBUF_INCLUDED_other_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "post.eproto.pb.h"
#include "social.eproto.pb.h"
#include "huodong.eproto.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_other_2eproto 

namespace protobuf_other_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_other_2eproto
namespace protocol {
namespace game {
class huodong_list_t;
class huodong_list_tDefaultTypeInternal;
extern huodong_list_tDefaultTypeInternal _huodong_list_t_default_instance_;
class player_guids_list_t;
class player_guids_list_tDefaultTypeInternal;
extern player_guids_list_tDefaultTypeInternal _player_guids_list_t_default_instance_;
class post_list_t;
class post_list_tDefaultTypeInternal;
extern post_list_tDefaultTypeInternal _post_list_t_default_instance_;
class social_list_t;
class social_list_tDefaultTypeInternal;
extern social_list_tDefaultTypeInternal _social_list_t_default_instance_;
}  // namespace game
}  // namespace protocol
namespace google {
namespace protobuf {
template<> ::protocol::game::huodong_list_t* Arena::CreateMaybeMessage<::protocol::game::huodong_list_t>(Arena*);
template<> ::protocol::game::player_guids_list_t* Arena::CreateMaybeMessage<::protocol::game::player_guids_list_t>(Arena*);
template<> ::protocol::game::post_list_t* Arena::CreateMaybeMessage<::protocol::game::post_list_t>(Arena*);
template<> ::protocol::game::social_list_t* Arena::CreateMaybeMessage<::protocol::game::social_list_t>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protocol {
namespace game {

// ===================================================================

class post_list_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.game.post_list_t) */ {
 public:
  post_list_t();
  virtual ~post_list_t();

  post_list_t(const post_list_t& from);

  inline post_list_t& operator=(const post_list_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  post_list_t(post_list_t&& from) noexcept
    : post_list_t() {
    *this = ::std::move(from);
  }

  inline post_list_t& operator=(post_list_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const post_list_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const post_list_t* internal_default_instance() {
    return reinterpret_cast<const post_list_t*>(
               &_post_list_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(post_list_t* other);
  friend void swap(post_list_t& a, post_list_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline post_list_t* New() const final {
    return CreateMaybeMessage<post_list_t>(NULL);
  }

  post_list_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<post_list_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const post_list_t& from);
  void MergeFrom(const post_list_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(post_list_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .dhc.post_t post_record = 1;
  int post_record_size() const;
  void clear_post_record();
  static const int kPostRecordFieldNumber = 1;
  ::dhc::post_t* mutable_post_record(int index);
  ::google::protobuf::RepeatedPtrField< ::dhc::post_t >*
      mutable_post_record();
  const ::dhc::post_t& post_record(int index) const;
  ::dhc::post_t* add_post_record();
  const ::google::protobuf::RepeatedPtrField< ::dhc::post_t >&
      post_record() const;

  // @@protoc_insertion_point(class_scope:protocol.game.post_list_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::dhc::post_t > post_record_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_other_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class social_list_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.game.social_list_t) */ {
 public:
  social_list_t();
  virtual ~social_list_t();

  social_list_t(const social_list_t& from);

  inline social_list_t& operator=(const social_list_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  social_list_t(social_list_t&& from) noexcept
    : social_list_t() {
    *this = ::std::move(from);
  }

  inline social_list_t& operator=(social_list_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const social_list_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const social_list_t* internal_default_instance() {
    return reinterpret_cast<const social_list_t*>(
               &_social_list_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(social_list_t* other);
  friend void swap(social_list_t& a, social_list_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline social_list_t* New() const final {
    return CreateMaybeMessage<social_list_t>(NULL);
  }

  social_list_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<social_list_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const social_list_t& from);
  void MergeFrom(const social_list_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(social_list_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .dhc.social_t socials = 1;
  int socials_size() const;
  void clear_socials();
  static const int kSocialsFieldNumber = 1;
  ::dhc::social_t* mutable_socials(int index);
  ::google::protobuf::RepeatedPtrField< ::dhc::social_t >*
      mutable_socials();
  const ::dhc::social_t& socials(int index) const;
  ::dhc::social_t* add_socials();
  const ::google::protobuf::RepeatedPtrField< ::dhc::social_t >&
      socials() const;

  // @@protoc_insertion_point(class_scope:protocol.game.social_list_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::dhc::social_t > socials_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_other_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class huodong_list_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.game.huodong_list_t) */ {
 public:
  huodong_list_t();
  virtual ~huodong_list_t();

  huodong_list_t(const huodong_list_t& from);

  inline huodong_list_t& operator=(const huodong_list_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  huodong_list_t(huodong_list_t&& from) noexcept
    : huodong_list_t() {
    *this = ::std::move(from);
  }

  inline huodong_list_t& operator=(huodong_list_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const huodong_list_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const huodong_list_t* internal_default_instance() {
    return reinterpret_cast<const huodong_list_t*>(
               &_huodong_list_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(huodong_list_t* other);
  friend void swap(huodong_list_t& a, huodong_list_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline huodong_list_t* New() const final {
    return CreateMaybeMessage<huodong_list_t>(NULL);
  }

  huodong_list_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<huodong_list_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const huodong_list_t& from);
  void MergeFrom(const huodong_list_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(huodong_list_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .dhc.huodong_t huodongs = 1;
  int huodongs_size() const;
  void clear_huodongs();
  static const int kHuodongsFieldNumber = 1;
  ::dhc::huodong_t* mutable_huodongs(int index);
  ::google::protobuf::RepeatedPtrField< ::dhc::huodong_t >*
      mutable_huodongs();
  const ::dhc::huodong_t& huodongs(int index) const;
  ::dhc::huodong_t* add_huodongs();
  const ::google::protobuf::RepeatedPtrField< ::dhc::huodong_t >&
      huodongs() const;

  // @@protoc_insertion_point(class_scope:protocol.game.huodong_list_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::dhc::huodong_t > huodongs_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_other_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class player_guids_list_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.game.player_guids_list_t) */ {
 public:
  player_guids_list_t();
  virtual ~player_guids_list_t();

  player_guids_list_t(const player_guids_list_t& from);

  inline player_guids_list_t& operator=(const player_guids_list_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  player_guids_list_t(player_guids_list_t&& from) noexcept
    : player_guids_list_t() {
    *this = ::std::move(from);
  }

  inline player_guids_list_t& operator=(player_guids_list_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const player_guids_list_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const player_guids_list_t* internal_default_instance() {
    return reinterpret_cast<const player_guids_list_t*>(
               &_player_guids_list_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(player_guids_list_t* other);
  friend void swap(player_guids_list_t& a, player_guids_list_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline player_guids_list_t* New() const final {
    return CreateMaybeMessage<player_guids_list_t>(NULL);
  }

  player_guids_list_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<player_guids_list_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const player_guids_list_t& from);
  void MergeFrom(const player_guids_list_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(player_guids_list_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 player_guids = 1;
  int player_guids_size() const;
  void clear_player_guids();
  static const int kPlayerGuidsFieldNumber = 1;
  ::google::protobuf::uint64 player_guids(int index) const;
  void set_player_guids(int index, ::google::protobuf::uint64 value);
  void add_player_guids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      player_guids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_player_guids();

  // @@protoc_insertion_point(class_scope:protocol.game.player_guids_list_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > player_guids_;
  mutable int _player_guids_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_other_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// post_list_t

// repeated .dhc.post_t post_record = 1;
inline int post_list_t::post_record_size() const {
  return post_record_.size();
}
inline ::dhc::post_t* post_list_t::mutable_post_record(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.game.post_list_t.post_record)
  return post_record_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::dhc::post_t >*
post_list_t::mutable_post_record() {
  // @@protoc_insertion_point(field_mutable_list:protocol.game.post_list_t.post_record)
  return &post_record_;
}
inline const ::dhc::post_t& post_list_t::post_record(int index) const {
  // @@protoc_insertion_point(field_get:protocol.game.post_list_t.post_record)
  return post_record_.Get(index);
}
inline ::dhc::post_t* post_list_t::add_post_record() {
  // @@protoc_insertion_point(field_add:protocol.game.post_list_t.post_record)
  return post_record_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dhc::post_t >&
post_list_t::post_record() const {
  // @@protoc_insertion_point(field_list:protocol.game.post_list_t.post_record)
  return post_record_;
}

// -------------------------------------------------------------------

// social_list_t

// repeated .dhc.social_t socials = 1;
inline int social_list_t::socials_size() const {
  return socials_.size();
}
inline ::dhc::social_t* social_list_t::mutable_socials(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.game.social_list_t.socials)
  return socials_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::dhc::social_t >*
social_list_t::mutable_socials() {
  // @@protoc_insertion_point(field_mutable_list:protocol.game.social_list_t.socials)
  return &socials_;
}
inline const ::dhc::social_t& social_list_t::socials(int index) const {
  // @@protoc_insertion_point(field_get:protocol.game.social_list_t.socials)
  return socials_.Get(index);
}
inline ::dhc::social_t* social_list_t::add_socials() {
  // @@protoc_insertion_point(field_add:protocol.game.social_list_t.socials)
  return socials_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dhc::social_t >&
social_list_t::socials() const {
  // @@protoc_insertion_point(field_list:protocol.game.social_list_t.socials)
  return socials_;
}

// -------------------------------------------------------------------

// huodong_list_t

// repeated .dhc.huodong_t huodongs = 1;
inline int huodong_list_t::huodongs_size() const {
  return huodongs_.size();
}
inline ::dhc::huodong_t* huodong_list_t::mutable_huodongs(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.game.huodong_list_t.huodongs)
  return huodongs_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::dhc::huodong_t >*
huodong_list_t::mutable_huodongs() {
  // @@protoc_insertion_point(field_mutable_list:protocol.game.huodong_list_t.huodongs)
  return &huodongs_;
}
inline const ::dhc::huodong_t& huodong_list_t::huodongs(int index) const {
  // @@protoc_insertion_point(field_get:protocol.game.huodong_list_t.huodongs)
  return huodongs_.Get(index);
}
inline ::dhc::huodong_t* huodong_list_t::add_huodongs() {
  // @@protoc_insertion_point(field_add:protocol.game.huodong_list_t.huodongs)
  return huodongs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dhc::huodong_t >&
huodong_list_t::huodongs() const {
  // @@protoc_insertion_point(field_list:protocol.game.huodong_list_t.huodongs)
  return huodongs_;
}

// -------------------------------------------------------------------

// player_guids_list_t

// repeated uint64 player_guids = 1;
inline int player_guids_list_t::player_guids_size() const {
  return player_guids_.size();
}
inline void player_guids_list_t::clear_player_guids() {
  set_changed();
  player_guids_.Clear();
}
inline ::google::protobuf::uint64 player_guids_list_t::player_guids(int index) const {
  // @@protoc_insertion_point(field_get:protocol.game.player_guids_list_t.player_guids)
  return player_guids_.Get(index);
}
inline void player_guids_list_t::set_player_guids(int index, ::google::protobuf::uint64 value) {
  set_changed();
  player_guids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protocol.game.player_guids_list_t.player_guids)
}
inline void player_guids_list_t::add_player_guids(::google::protobuf::uint64 value) {
  set_changed();
  player_guids_.Add(value);
  // @@protoc_insertion_point(field_add:protocol.game.player_guids_list_t.player_guids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
player_guids_list_t::player_guids() const {
  // @@protoc_insertion_point(field_list:protocol.game.player_guids_list_t.player_guids)
  return player_guids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
player_guids_list_t::mutable_player_guids() {
  set_changed();
  // @@protoc_insertion_point(field_mutable_list:protocol.game.player_guids_list_t.player_guids)
  return &player_guids_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game
}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_other_2eproto
