// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.eproto

#ifndef PROTOBUF_INCLUDED_post_2eeproto
#define PROTOBUF_INCLUDED_post_2eeproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_post_2eeproto 

namespace protobuf_post_2eeproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_post_2eeproto
namespace dhc {
class post_t;
class post_tDefaultTypeInternal;
extern post_tDefaultTypeInternal _post_t_default_instance_;
}  // namespace dhc
namespace google {
namespace protobuf {
template<> ::dhc::post_t* Arena::CreateMaybeMessage<::dhc::post_t>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dhc {

// ===================================================================

class post_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dhc.post_t) */ {
 public:
  post_t();
  virtual ~post_t();

  post_t(const post_t& from);

  inline post_t& operator=(const post_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  post_t(post_t&& from) noexcept
    : post_t() {
    *this = ::std::move(from);
  }

  inline post_t& operator=(post_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const post_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const post_t* internal_default_instance() {
    return reinterpret_cast<const post_t*>(
               &_post_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(post_t* other);
  friend void swap(post_t& a, post_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline post_t* New() const final {
    return CreateMaybeMessage<post_t>(NULL);
  }

  post_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<post_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const post_t& from);
  void MergeFrom(const post_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(post_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 type = 8;
  int type_size() const;
  void clear_type();
  static const int kTypeFieldNumber = 8;
  ::google::protobuf::int32 type(int index) const;
  void set_type(int index, ::google::protobuf::int32 value);
  void add_type(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      type() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_type();

  // repeated int32 value1 = 9;
  int value1_size() const;
  void clear_value1();
  static const int kValue1FieldNumber = 9;
  ::google::protobuf::int32 value1(int index) const;
  void set_value1(int index, ::google::protobuf::int32 value);
  void add_value1(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      value1() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_value1();

  // repeated int32 value2 = 10;
  int value2_size() const;
  void clear_value2();
  static const int kValue2FieldNumber = 10;
  ::google::protobuf::int32 value2(int index) const;
  void set_value2(int index, ::google::protobuf::int32 value);
  void add_value2(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      value2() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_value2();

  // repeated int32 value3 = 11;
  int value3_size() const;
  void clear_value3();
  static const int kValue3FieldNumber = 11;
  ::google::protobuf::int32 value3(int index) const;
  void set_value3(int index, ::google::protobuf::int32 value);
  void add_value3(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      value3() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_value3();

  // string title = 5;
  void clear_title();
  static const int kTitleFieldNumber = 5;
  const ::std::string& title() const;
  void set_title(const ::std::string& value);
  #if LANG_CXX11
  void set_title(::std::string&& value);
  #endif
  void set_title(const char* value);
  void set_title(const char* value, size_t size);
  ::std::string* mutable_title();
  ::std::string* release_title();
  void set_allocated_title(::std::string* title);

  // string text = 6;
  void clear_text();
  static const int kTextFieldNumber = 6;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // string sender_name = 7;
  void clear_sender_name();
  static const int kSenderNameFieldNumber = 7;
  const ::std::string& sender_name() const;
  void set_sender_name(const ::std::string& value);
  #if LANG_CXX11
  void set_sender_name(::std::string&& value);
  #endif
  void set_sender_name(const char* value);
  void set_sender_name(const char* value, size_t size);
  ::std::string* mutable_sender_name();
  ::std::string* release_sender_name();
  void set_allocated_sender_name(::std::string* sender_name);

  // uint64 pid = 1;
  void clear_pid();
  static const int kPidFieldNumber = 1;
  ::google::protobuf::uint64 pid() const;
  void set_pid(::google::protobuf::uint64 value);

  // uint64 guid = 2;
  void clear_guid();
  static const int kGuidFieldNumber = 2;
  ::google::protobuf::uint64 guid() const;
  void set_guid(::google::protobuf::uint64 value);

  // uint64 receiver_guid = 3;
  void clear_receiver_guid();
  static const int kReceiverGuidFieldNumber = 3;
  ::google::protobuf::uint64 receiver_guid() const;
  void set_receiver_guid(::google::protobuf::uint64 value);

  // uint64 sender_date = 4;
  void clear_sender_date();
  static const int kSenderDateFieldNumber = 4;
  ::google::protobuf::uint64 sender_date() const;
  void set_sender_date(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:dhc.post_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > type_;
  mutable int _type_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > value1_;
  mutable int _value1_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > value2_;
  mutable int _value2_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > value3_;
  mutable int _value3_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr title_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::google::protobuf::internal::ArenaStringPtr sender_name_;
  ::google::protobuf::uint64 pid_;
  ::google::protobuf::uint64 guid_;
  ::google::protobuf::uint64 receiver_guid_;
  ::google::protobuf::uint64 sender_date_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_post_2eeproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// post_t

// uint64 pid = 1;
inline void post_t::clear_pid() {
  set_changed();
  pid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 post_t::pid() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.pid)
  return pid_;
}
inline void post_t::set_pid(::google::protobuf::uint64 value) {
  set_changed();
  
  pid_ = value;
  // @@protoc_insertion_point(field_set:dhc.post_t.pid)
}

// uint64 guid = 2;
inline void post_t::clear_guid() {
  set_changed();
  guid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 post_t::guid() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.guid)
  return guid_;
}
inline void post_t::set_guid(::google::protobuf::uint64 value) {
  set_changed();
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:dhc.post_t.guid)
}

// uint64 receiver_guid = 3;
inline void post_t::clear_receiver_guid() {
  set_changed();
  receiver_guid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 post_t::receiver_guid() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.receiver_guid)
  return receiver_guid_;
}
inline void post_t::set_receiver_guid(::google::protobuf::uint64 value) {
  set_changed();
  
  receiver_guid_ = value;
  // @@protoc_insertion_point(field_set:dhc.post_t.receiver_guid)
}

// uint64 sender_date = 4;
inline void post_t::clear_sender_date() {
  set_changed();
  sender_date_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 post_t::sender_date() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.sender_date)
  return sender_date_;
}
inline void post_t::set_sender_date(::google::protobuf::uint64 value) {
  set_changed();
  
  sender_date_ = value;
  // @@protoc_insertion_point(field_set:dhc.post_t.sender_date)
}

// string title = 5;
inline void post_t::clear_title() {
  set_changed();
  title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& post_t::title() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.title)
  return title_.GetNoArena();
}
inline void post_t::set_title(const ::std::string& value) {
  set_changed();
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dhc.post_t.title)
}
#if LANG_CXX11
inline void post_t::set_title(::std::string&& value) {
  set_changed();
  
  title_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dhc.post_t.title)
}
#endif
inline void post_t::set_title(const char* value) {
  set_changed();
  GOOGLE_DCHECK(value != NULL);
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dhc.post_t.title)
}
inline void post_t::set_title(const char* value, size_t size) {
  set_changed();
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dhc.post_t.title)
}
inline ::std::string* post_t::mutable_title() {
  set_changed();
  
  // @@protoc_insertion_point(field_mutable:dhc.post_t.title)
  return title_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* post_t::release_title() {
  set_changed();
  // @@protoc_insertion_point(field_release:dhc.post_t.title)
  
  return title_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void post_t::set_allocated_title(::std::string* title) {
  set_changed();
  if (title != NULL) {
    
  } else {
    
  }
  title_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), title);
  // @@protoc_insertion_point(field_set_allocated:dhc.post_t.title)
}

// string text = 6;
inline void post_t::clear_text() {
  set_changed();
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& post_t::text() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.text)
  return text_.GetNoArena();
}
inline void post_t::set_text(const ::std::string& value) {
  set_changed();
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dhc.post_t.text)
}
#if LANG_CXX11
inline void post_t::set_text(::std::string&& value) {
  set_changed();
  
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dhc.post_t.text)
}
#endif
inline void post_t::set_text(const char* value) {
  set_changed();
  GOOGLE_DCHECK(value != NULL);
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dhc.post_t.text)
}
inline void post_t::set_text(const char* value, size_t size) {
  set_changed();
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dhc.post_t.text)
}
inline ::std::string* post_t::mutable_text() {
  set_changed();
  
  // @@protoc_insertion_point(field_mutable:dhc.post_t.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* post_t::release_text() {
  set_changed();
  // @@protoc_insertion_point(field_release:dhc.post_t.text)
  
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void post_t::set_allocated_text(::std::string* text) {
  set_changed();
  if (text != NULL) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:dhc.post_t.text)
}

// string sender_name = 7;
inline void post_t::clear_sender_name() {
  set_changed();
  sender_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& post_t::sender_name() const {
  // @@protoc_insertion_point(field_get:dhc.post_t.sender_name)
  return sender_name_.GetNoArena();
}
inline void post_t::set_sender_name(const ::std::string& value) {
  set_changed();
  
  sender_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dhc.post_t.sender_name)
}
#if LANG_CXX11
inline void post_t::set_sender_name(::std::string&& value) {
  set_changed();
  
  sender_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dhc.post_t.sender_name)
}
#endif
inline void post_t::set_sender_name(const char* value) {
  set_changed();
  GOOGLE_DCHECK(value != NULL);
  
  sender_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dhc.post_t.sender_name)
}
inline void post_t::set_sender_name(const char* value, size_t size) {
  set_changed();
  
  sender_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dhc.post_t.sender_name)
}
inline ::std::string* post_t::mutable_sender_name() {
  set_changed();
  
  // @@protoc_insertion_point(field_mutable:dhc.post_t.sender_name)
  return sender_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* post_t::release_sender_name() {
  set_changed();
  // @@protoc_insertion_point(field_release:dhc.post_t.sender_name)
  
  return sender_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void post_t::set_allocated_sender_name(::std::string* sender_name) {
  set_changed();
  if (sender_name != NULL) {
    
  } else {
    
  }
  sender_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender_name);
  // @@protoc_insertion_point(field_set_allocated:dhc.post_t.sender_name)
}

// repeated int32 type = 8;
inline int post_t::type_size() const {
  return type_.size();
}
inline void post_t::clear_type() {
  set_changed();
  type_.Clear();
}
inline ::google::protobuf::int32 post_t::type(int index) const {
  // @@protoc_insertion_point(field_get:dhc.post_t.type)
  return type_.Get(index);
}
inline void post_t::set_type(int index, ::google::protobuf::int32 value) {
  set_changed();
  type_.Set(index, value);
  // @@protoc_insertion_point(field_set:dhc.post_t.type)
}
inline void post_t::add_type(::google::protobuf::int32 value) {
  set_changed();
  type_.Add(value);
  // @@protoc_insertion_point(field_add:dhc.post_t.type)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
post_t::type() const {
  // @@protoc_insertion_point(field_list:dhc.post_t.type)
  return type_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
post_t::mutable_type() {
  set_changed();
  // @@protoc_insertion_point(field_mutable_list:dhc.post_t.type)
  return &type_;
}

// repeated int32 value1 = 9;
inline int post_t::value1_size() const {
  return value1_.size();
}
inline void post_t::clear_value1() {
  set_changed();
  value1_.Clear();
}
inline ::google::protobuf::int32 post_t::value1(int index) const {
  // @@protoc_insertion_point(field_get:dhc.post_t.value1)
  return value1_.Get(index);
}
inline void post_t::set_value1(int index, ::google::protobuf::int32 value) {
  set_changed();
  value1_.Set(index, value);
  // @@protoc_insertion_point(field_set:dhc.post_t.value1)
}
inline void post_t::add_value1(::google::protobuf::int32 value) {
  set_changed();
  value1_.Add(value);
  // @@protoc_insertion_point(field_add:dhc.post_t.value1)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
post_t::value1() const {
  // @@protoc_insertion_point(field_list:dhc.post_t.value1)
  return value1_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
post_t::mutable_value1() {
  set_changed();
  // @@protoc_insertion_point(field_mutable_list:dhc.post_t.value1)
  return &value1_;
}

// repeated int32 value2 = 10;
inline int post_t::value2_size() const {
  return value2_.size();
}
inline void post_t::clear_value2() {
  set_changed();
  value2_.Clear();
}
inline ::google::protobuf::int32 post_t::value2(int index) const {
  // @@protoc_insertion_point(field_get:dhc.post_t.value2)
  return value2_.Get(index);
}
inline void post_t::set_value2(int index, ::google::protobuf::int32 value) {
  set_changed();
  value2_.Set(index, value);
  // @@protoc_insertion_point(field_set:dhc.post_t.value2)
}
inline void post_t::add_value2(::google::protobuf::int32 value) {
  set_changed();
  value2_.Add(value);
  // @@protoc_insertion_point(field_add:dhc.post_t.value2)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
post_t::value2() const {
  // @@protoc_insertion_point(field_list:dhc.post_t.value2)
  return value2_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
post_t::mutable_value2() {
  set_changed();
  // @@protoc_insertion_point(field_mutable_list:dhc.post_t.value2)
  return &value2_;
}

// repeated int32 value3 = 11;
inline int post_t::value3_size() const {
  return value3_.size();
}
inline void post_t::clear_value3() {
  set_changed();
  value3_.Clear();
}
inline ::google::protobuf::int32 post_t::value3(int index) const {
  // @@protoc_insertion_point(field_get:dhc.post_t.value3)
  return value3_.Get(index);
}
inline void post_t::set_value3(int index, ::google::protobuf::int32 value) {
  set_changed();
  value3_.Set(index, value);
  // @@protoc_insertion_point(field_set:dhc.post_t.value3)
}
inline void post_t::add_value3(::google::protobuf::int32 value) {
  set_changed();
  value3_.Add(value);
  // @@protoc_insertion_point(field_add:dhc.post_t.value3)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
post_t::value3() const {
  // @@protoc_insertion_point(field_list:dhc.post_t.value3)
  return value3_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
post_t::mutable_value3() {
  set_changed();
  // @@protoc_insertion_point(field_mutable_list:dhc.post_t.value3)
  return &value3_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dhc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_post_2eeproto
